#=
Sources:
- https://github.com/CSCsw/ColPack/tree/master/Examples
=#

## Coloring on general graphs

const COLORING_METHODS = [
    "DISTANCE_ONE",
    "ACYCLIC",
    "ACYCLIC_FOR_INDIRECT_RECOVERY",
    "STAR",
    "NAIVE_STAR",
    "RESTRICTED_STAR",
    "DISTANCE_TWO",
    # "TRIANGULAR",
]

const COLORING_ORDERS = [
    "NATURAL",
    "RANDOM",
    "LARGEST_FIRST",
    "SMALLEST_LAST",
    "DYNAMIC_LARGEST_FIRST",
    "INCIDENCE_DEGREE",
    "DISTANCE_TWO_SMALLEST_LAST",
    "DISTANCE_TWO_LARGEST_FIRST",
    "DISTANCE_TWO_INCIDENCE_DEGREE",
]

## Partial coloring on bipartite graphs

const PARTIAL_COLORING_METHODS = [
    "COLUMN_PARTIAL_DISTANCE_TWO",
    "ROW_PARTIAL_DISTANCE_TWO",
]

const PARTIAL_COLORING_ORDERS = [
    "NATURAL",
    "RANDOM",
    "LARGEST_FIRST",
    "DYNAMIC_LARGEST_FIRST",
    "SMALLEST_LAST",
    "INCIDENCE_DEGREE",
]

## Bicoloring on bipartite graphs

const BICOLORING_METHODS = [
    "IMPLICIT_COVERING__STAR_BICOLORING",
    "EXPLICIT_COVERING__STAR_BICOLORING",
    "EXPLICIT_COVERING__MODIFIED_STAR_BICOLORING",
    "IMPLICIT_COVERING__GREEDY_STAR_BICOLORING",
]

const BICOLORING_ORDERS = [
    "NATURAL",
    "RANDOM",
    "LARGEST_FIRST",
    "DYNAMIC_LARGEST_FIRST",
    "SMALLEST_LAST",
    "INCIDENCE_DEGREE",
    # "SELECTIVE_LARGEST_FIRST",
    # "SELECTIVE_SMALLEST_LAST",
    # "SELECTIVE_INCIDENCE_DEGREE",
]
